### ISSUE TITLE
Option to hide Hue,saturation component

### ISSUE THREAD

**Issue by samiksha-singla** [stayradiated/react-colorpicker#15]
Hi

Awesome work , but I got a requirement where I need to hide to the Hue, saturation components. Is there any property by which I can hide this ?

**Comment by stayradiated** [comment]
You could edit the CSS to hide it.

``` css
.colorpicker .details .hsv {
  display: none;
}
```
